// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtF5mQAFAauZDWW4JIALujX_I2u4sVWg0',
    appId: '1:208539895577:web:bdc605865ce22c820e2788',
    messagingSenderId: '208539895577',
    projectId: 'istakhara',
    authDomain: 'istakhara.firebaseapp.com',
    storageBucket: 'istakhara.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUggY1bONuiL-2rQqSHK1n1HxJdeo2PE',
    appId: '1:208539895577:android:1ccf43f56d4cea4f0e2788',
    messagingSenderId: '208539895577',
    projectId: 'istakhara',
    storageBucket: 'istakhara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCUGZZQsgltxsQAodRIo0ce-IjQ4S7AlQ',
    appId: '1:208539895577:ios:f6345a714075ac860e2788',
    messagingSenderId: '208539895577',
    projectId: 'istakhara',
    storageBucket: 'istakhara.appspot.com',
    iosBundleId: 'com.example.travellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCUGZZQsgltxsQAodRIo0ce-IjQ4S7AlQ',
    appId: '1:208539895577:ios:f69c67bed381d4e00e2788',
    messagingSenderId: '208539895577',
    projectId: 'istakhara',
    storageBucket: 'istakhara.appspot.com',
    iosBundleId: 'com.example.travellingApp.RunnerTests',
  );
}
